"""crear tabla clientes crm

Revision ID: 3473c4544b7f
Revises: 5dd14b72e427
Create Date: 2026-04-04 21:47:53.588060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3473c4544b7f'
down_revision = '5dd14b72e427'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('clientes')
    # ### end Alembic commands ###
