"""crear tabla presentaciones

Revision ID: 5dd14b72e427
Revises: f53fcae04717
Create Date: 2026-04-04 20:26:00.762298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dd14b72e427'
down_revision = 'f53fcae04717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('presentaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('id_unidad', sa.Integer(), nullable=False),
    sa.Column('cantidad_equivalente', sa.Float(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_unidad'], ['unidad_medida.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('presentaciones')
    # ### end Alembic commands ###
