"""procProd

Revision ID: 742afb917c33
Revises: e15c081b7107
Create Date: 2026-04-04 14:23:26.037366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '742afb917c33'
down_revision = 'e15c081b7107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('procesos_productivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('procesos_productivos')
    # ### end Alembic commands ###
