"""agregar campos de tipo y conversion a unidades

Revision ID: ce609f1d81a1
Revises: e15c081b7107
Create Date: 2026-04-04 16:08:04.971412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce609f1d81a1'
down_revision = 'e15c081b7107'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unidad_medida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('abreviatura', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('es_base', sa.Boolean(), nullable=False),
    sa.Column('unidad_base_id', sa.Integer(), nullable=True),
    sa.Column('valor_conversion', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['unidad_base_id'], ['unidad_medida.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abreviatura'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unidad_medida')
    # ### end Alembic commands ###
