"""proveedores_6

Revision ID: e15c081b7107
Revises: cffcb274fa5e
Create Date: 2026-04-01 15:04:42.741499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e15c081b7107'
down_revision = 'cffcb274fa5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proveedores', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
