"""crear tabla materias primas

Revision ID: f53fcae04717
Revises: ce609f1d81a1
Create Date: 2026-04-04 17:34:50.916336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f53fcae04717'
down_revision = 'ce609f1d81a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materias_primas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.Column('id_unidad_base', sa.Integer(), nullable=False),
    sa.Column('stock_minimo', sa.Float(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_unidad_base'], ['unidad_medida.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('materias_primas')
    # ### end Alembic commands ###
